services:
  frontend:
    container_name: sanos_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
    networks:
      - sanos-network
    restart: always

networks:
  sanos-network:
    external: true